<template><div><h1 id="数据字典" tabindex="-1"><a class="header-anchor" href="#数据字典" aria-hidden="true">#</a> 数据字典</h1>
<DictDemo /><details class="custom-container details"><summary>点击查看代码</summary>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>template<span class="token operator">></span>
    案例<span class="token number">1</span><span class="token operator">:</span><span class="token operator">&lt;</span>br<span class="token operator">></span>
    testDate的value为<span class="token number">1</span>的时候的数值是：
    <span class="token operator">&lt;</span>DictCom <span class="token operator">:</span>options<span class="token operator">=</span><span class="token string">"testDate"</span> value<span class="token operator">=</span><span class="token string">"1"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>template #<span class="token keyword">default</span><span class="token operator">=</span><span class="token string">"scope"</span><span class="token operator">></span>value1的映射是：<span class="token punctuation">{</span><span class="token punctuation">{</span> scope<span class="token punctuation">.</span>label <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>template<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>DictCom<span class="token operator">></span>
    <span class="token operator">&lt;</span>br<span class="token operator">></span>
    <span class="token operator">&lt;</span>br<span class="token operator">></span>
    案例<span class="token number">2</span><span class="token operator">:</span><span class="token operator">&lt;</span>br<span class="token operator">></span>
    <span class="token operator">&lt;</span>el<span class="token operator">-</span>select v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"value"</span> placeholder<span class="token operator">=</span><span class="token string">"Select"</span> size<span class="token operator">=</span><span class="token string">"large"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>el<span class="token operator">-</span>option v<span class="token operator">-</span><span class="token keyword">for</span><span class="token operator">=</span><span class="token string">"item in testDate"</span> <span class="token operator">:</span>key<span class="token operator">=</span><span class="token string">"item.value"</span> <span class="token operator">:</span>label<span class="token operator">=</span><span class="token string">"item.label"</span> <span class="token operator">:</span>value<span class="token operator">=</span><span class="token string">"item.value"</span> <span class="token operator">/</span><span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>el<span class="token operator">-</span>select<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">/</span>template<span class="token operator">></span>
<span class="token operator">&lt;</span>script setup lang<span class="token operator">=</span><span class="token string">"ts"</span><span class="token operator">></span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> useDict <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../components/DictFn'</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> testDate <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">useDict</span><span class="token punctuation">(</span><span class="token string">'testDate'</span><span class="token punctuation">)</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> ref <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue'</span>
<span class="token keyword">let</span> value <span class="token operator">=</span> <span class="token function">ref</span><span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></details>
</div></template>


